---
title: "Business Analytics-Group Project 1.Version1"
author: "Khushboo Yadav"
date: "11/24/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

rm(list=ls()) # This code will clear your environment each time you run all. 
```

#### 1.Import Libraries
```{r, warning = FALSE}
library(plyr)
library(ggplot2)
library(caret)
library(party)
# install.packages('rpart.plot')
library(rpart)
library(rpart.plot)
```

#### 2.Reading the dataset  
```{r}
Churn_Train <- read.csv("Churn_Train.csv") 
load("Customers_To_Predict.RData")
summary(Churn_Train)
```
# analysing count of NA value in the dataset
```{r}
sapply(Churn_Train, function(x) sum(is.na(x))) # NA data
sapply(Customers_To_Predict,function(x) sum(is.na(x))) # no NA data
```

## Exploratory Data Analysis
```{r}
Churn_Train %>% 
  filter(churn_yes == 1) %>%
  ggplot(mapping = aes(x = num_cust_serv_calls)) +
  geom_histogram(aes(fill = "steelblue"), binwidth = 1)

Churn_Train %>% 
  count(churn_yes)

Churn_Train %>% 
  filter(churn_yes == 1 & num_cust_serv_calls >= 1 & num_cust_serv_calls <= 4)%>% 
  summarise("% churned after making betw 1 and 4 cust service calls" = n()/707*100)

Churn_Train %>% 
  filter(churn_yes== 1) -> churn_cust
 
Churn_Train %>% 
  filter(churn_yes== 1) %>%
  ggplot(mapping = aes(x = intl_plan_yes)) +
  geom_histogram(aes(fill = churn_yes), stat = "count")
```

#### removing NA values
```{r}
Churn_Train <- na.omit(Churn_Train)
```

# Removing state and area codes from the dataset
```{r}
Churn_Train<-Churn_Train[,-c(1,3)] 


Customers_To_Predict<-Customers_To_Predict[,-c(1,3)]
```
#### data manipulation
```{r}
##updating the values of International plan , voice mail plan and churn to 1 or 0

#for Churn_Train data
Churn_Train$international_plan<-ifelse(Churn_Train$international_plan=="yes",1,0)
Churn_Train$voice_mail_plan<- ifelse(Churn_Train$voice_mail_plan=="yes",1,0)
Churn_Train$churn<- ifelse(Churn_Train$churn=="yes",1,0)

#for Customer to predict data
Customers_To_Predict$international_plan<-ifelse(Customers_To_Predict$international_plan=="yes",1,0)
Customers_To_Predict$voice_mail_plan <- ifelse(Customers_To_Predict$voice_mail_plan=="yes",1,0)

##Factorization of above data
#for Churn_Train data
Churn_Train$international_plan<-as.factor(Churn_Train$international_plan)
Churn_Train$voice_mail_plan <-as.factor(Churn_Train$voice_mail_plan)
Churn_Train$churn<- as.factor(Churn_Train$churn)


#for Customer_To_Predict data
Customers_To_Predict$international_plan <- as.factor(Customers_To_Predict$international_plan)
Customers_To_Predict$voice_mail_plan <- as.factor(Customers_To_Predict$voice_mail_plan)


Decision_tree_CPT<- Customers_To_Predict # copied the data for decision tree

summary(Churn_Train)
str(Churn_Train)

```

##normalization not needed
```{r}

```

#logistic regression
```{r}
Model_ABC_Wireless <- glm(churn ~ .,family=binomial(link="logit"),data=Churn_Train)
summary(Model_ABC_Wireless)
```

# Anova
```{r}
anova(Model_ABC_Wireless, test="Chisq")
```


#Prediction
```{r}

Churn_Prob <- predict(Model_ABC_Wireless, newdata = Customers_To_Predict, type = 'response')

Churn_Probb <- ifelse(Churn_Prob > 0.5,1,0) # Assigning 1 to 0.5 and above  and 0 to 0.5 below
Customers_To_Predict$Churn<-Churn_Probb # assigning Churn probability to new Column Churn


Customers_To_Predict$Churn<-as.factor(Customers_To_Predict$Churn)
str(Customers_To_Predict)

table(Customers_To_Predict$Churn)

plot(Customers_To_Predict$Churn,xlab="1= customer likely to churn ,0= customer will not churn" , ylab="Customers",main="Prediction of customers who are likely to churn",col="sky blue")

## 55 customers are likely to churn and 945 are not likely to churn
```
# decision Tree
```{r}
DC_Tree <- ctree(Churn_Train$churn~ ., Churn_Train)

dcplot<-rpart(Churn_Train$churn ~.,data=Churn_Train,method='class')

rpart.plot(dcplot,extra=106)

plot(DC_Tree, type='simple')

pred_tree <- predict(DC_Tree, Decision_tree_CPT)

table(pred_tree) # 0=912, customer not likely to churn ,1=88 ,customer likely to churn 

plot(pred_tree,xlab="1= customer likely to churn ,0= customer will not churn" , ylab="Customers",main="Prediction of customers who are likely to churn",col="orange")
```
